version: '3.8'
services:
  sliver:
    build: .
    image: sliver
    container_name: sliver_server
    volumes:
      - ./configs:/configs
      - ./phishlets:/phishlets 
      - ./payloads:/payloads 
      - ./misc:/misc
    command: daemon
    logging:
      driver: json-file
      options:
        max-size: 500m
        max-file: "10"
    ports:
      - 53:53
      - 80:80
      - 443:443
      - 8443:31337
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - "SETFCAP"
      - "NET_BIND_SERVICE"
      - "NET_RAW"